### ISSUE TITLE
Dawarich >= 0.24.1 support, PostGIS

### ISSUE THREAD

**Issue by sheyabernstein** [Cogitri/charts#50]
Dawarich >= 0.24.1 removes the dev entrypoints and starts using PostGIS. Starting from 0.26.0, [PostGIS will be the default](https://github.com/Freika/dawarich/releases/tag/0.24.1).

I've not been able to figure out how to use the standard entrypoints, I keep running into either blocked host errors, or HTTP 422 errors for post requests when settings `env.applicationHosts` (plural) to the value in my ingress and `env.secretKeyBase` to a random value. Setting `env.applicationHosts` also fails the pod liveness and readiness checks - also due to blocked hosts.

Perhaps someone with more Rails knowledge can elaborate here.

Regarding enable PostGIS, there's a [new migration](https://github.com/Freika/dawarich/blob/60061975d39b9a0de021591daa91ceeea0a6c718/db/migrate/20250123145155_enable_postgis_extension.rb#L4) that does this, but it'll fail since the dawarich deployments use a Postgres user that is not a superuser. Bitnami's postgresql image supports PostGIS, but the extension is disabled by default. I've confirmed that adding the following init container to the dawarich deployment resolves this, avoiding the need for elevating the dawarich user or manually enabling the extension.

```yaml
initContainers:
  {{ include "dawarich.initContainers" . | nindent 8 }}
  - name: postgis-init
    image: bitnami/postgresql:latest
    command:
      - /bin/sh
      - -c
      - |
        set -e
        psql -c "CREATE EXTENSION IF NOT EXISTS postgis;"
        echo "PostGIS extensions created successfully."
    env:
      - name: PGHOST
        value: {{ include "dawarich.fullname" . }}-postgresql
      - name: PGUSER
        value: postgres
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ include "dawarich.fullname" . }}-postgresql
            key: postgres-password
```

Either way, I have not opened a PR yet due to the hosts issue.

**Comment by Cogitri** [comment]
Oh thanks for the issue - somehow Renovate has stopped automatically opening PRs for new dawarich releases so I missed those - I'll look into it, thanks for providing your findings :)

**Comment by Cogitri** [comment]
Alright, fixed renovate, so I should be more on-top of future updates: https://github.com/Cogitri/charts/pull/53

**Comment by Cogitri** [comment]
I've released `dawarich` 0.6.0 which updates the container to 0.23.5 and fixes the host blocked errors you've noticed with the newer versions. Feel free to try updating to 0.24.x based on that, I'd be happy to review a PR :)

**Comment by sheyabernstein** [comment]
I'm getting `ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked hosts: dawarich-dev.cluster.local, dawarich-dev.cluster.local` on the master branch when trying to access the UI in my browser. The pod healthchecks are working fine.

Setting `env.secretKeyBase` doesn't seem to help.

Here are my values overrides:
```yaml
env:
  applicationHosts: dawarich-dev.cluster.local

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: dawarich-dev.cluster.local
      paths:
        - path: /
          pathType: ImplementationSpecific
```

**Comment by Cogitri** [comment]
See the release notes for the new values you have to set :)

**Comment by Cogitri** [comment]
https://github.com/Cogitri/charts/releases/tag/dawarich-0.6.0

**Comment by sheyabernstein** [comment]
Gotcha, updated these but getting HTTP 422 on POST /sign_in

**Comment by Cogitri** [comment]
Hm, that's odd, everything works perfectly for me - granted I use a proper domain instead of the coredns value, but that shouldn't really matter. What does the log of dawarich say?

**Comment by sheyabernstein** [comment]
Update: set the log level to debug and see some more logs, but nothing indicating the HTTP 422 reason.

```
dawarich-7786cd4bd-x2rd5 dawarich D, [2025-02-28T15:25:02.988033 #67] DEBUG -- :   User Load (1.8ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "user@domain.com"], ["LIMIT", 1]]
dawarich-7786cd4bd-x2rd5 dawarich I, [2025-02-28T15:25:02.992936 #67]  INFO -- : {"method":"POST","path":"/users/sign_in","format":"turbo_stream","controller":"Devise::SessionsController","action":"create","status":0,"allocations":11746,"duration":136.06,"view":0.0,"db":27.3}
dawarich-7786cd4bd-x2rd5 dawarich D, [2025-02-28T15:25:03.310820 #67] DEBUG -- :   Rendering layout layouts/application.html.erb
dawarich-7786cd4bd-x2rd5 dawarich D, [2025-02-28T15:25:03.311967 #67] DEBUG -- :   Rendering devise/sessions/new.html.erb within layouts/application
dawarich-7786cd4bd-x2rd5 dawarich I, [2025-02-28T15:25:05.080443 #67]  INFO -- : {"method":"POST","path":"/users/sign_in","format":"turbo_stream","controller":"Devise::SessionsController","action":"new","status":200,"allocations":325798,"duration":2084.24,"view":1788.02,"db":0.0}
```

Also, it seems that creating the postgis extension in an init container won't work since the migration still runs and apparently needs superuser access to check if already enabled. A crude fix would be an init container to elevate the dawarich user to superuser. What are your thoughts?

**Comment by sheyabernstein** [comment]
@Cogitri could you share your setup/values for hosts and ingress?

I've also tried changing `applicationProtocol` to https and using a remote domain for ingress (routed via cloudflared and traefik ingress) and get infinite HTTP 301 redirects.

**Comment by Cogitri** [comment]
Sure, my entire values.yaml is this (+resources, which I omitted here):

```
    keyBase:
      existingSecret: dawarich-secret-keybase
    postgresql:
      [...]
    redis:
      [...]
    dawarich:
      host: "myhost.example.org"
```

My ingress setup is a bit odd since I use tailscale, but in effect it sends a HTTP request with `Host: myhost.example.org` which is the important bit for dawarich/RoR to allow the request.
